services:
  backend:
    platform: linux/amd64
    build: ./Backend        
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/backend 
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    platform: linux/amd64
    build: ./Frontend/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend/frontend:/app
      - /app/node_modules
    depends_on:
      - backend